name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Checkout fwilhe2/melange
      uses: actions/checkout@v4.1.7
      with:
        repository: fwilhe2/melange
        ref: fwilhe-dev
        path: melange
    - name: Checkout fwilhe2/apko
      uses: actions/checkout@v4.1.7
      with:
        repository: fwilhe2/apko
        ref: fwilhe-dev
        path: apko
    - name: Setup Go environment
      uses: actions/setup-go@v5.0.1 
    - name: Build melange
      working-directory: melange
      run: |
        sudo make install
    - name: Build apko
      working-directory: apko
      run: |
        make apko
        sudo make install

    - run: which melange
    - run: which apko
    - run: melange version
    - run: apko version
    - run: sudo apt-get update && sudo apt-get -y install bubblewrap
    - run: melange build --arch x86_64 --keyring-append https://packages.wolfi.dev/os/wolfi-signing.rsa.pub --repository-append https://packages.wolfi.dev/os --log-level debug example.yaml

