name: CI
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Checkout fwilhe2/melange
      uses: actions/checkout@v4.1.7
      with:
        repository: fwilhe2/melange
        path: melange
    - name: Checkout fwilhe2/apko
      uses: actions/checkout@v4.1.7
      with:
        repository: fwilhe2/apko
        path: apko
    - name: Setup Go environment
      uses: actions/setup-go@v5.0.1 
    - name: Build melange
      working-directory: melange
      run: |
        sudo make install
    - name: Build apko
      working-directory: apko
      run: |
        sudo make install
